### ISSUE TITLE
Mod does not work in sandbox mode

### ISSUE THREAD

**Issue by DrNuenninger** [jaihysc/Factorio-AircraftRealism#11]
Tested on newest Version with all other mods disabled.

Fuel gauge does not show up and planes collide with everything no matter their speed.

**To Reproduce**
Start a new "Sandbox" type world.

I don't know if anyone uses the sandbox mode so this is probably does not need a fix. But a mention on the mod page would be very good. I spent an hour trying to get it to work. I tests some mods in sandbox first to see if I like them / feel they are balanced. Also it probably has something todo with there not beeing a "player" in sandbox mode.

**Comment by jaihysc** [comment]
Fixed for 1.2.1

You are correct in that the cause is because there is not a character for the player in sandbox mode.

The fix is strikingly simple, just not check for the character as it is not referenced in other portions of the mod.

Thanks!
