### ISSUE TITLE
Error when loading or installing mod on Factorio Server Manager

### ISSUE THREAD

**Issue by Suniver** [jaihysc/Factorio-AircraftRealism#18]
**General questions**
* Does the issue persist after updating to the latest version? 
YES
* Does the issue persist with all other mods disabled? 
YES

**General information**
* Factorio version 
1.1.50
* Mod version
1.4.0
* Other installed mods
Aircraft 1.8.4
AutoDesonstruct 0.3.0
Automatic Train Painter 1.1.4
Bottleneck 0.11.7
CanalBuilder (Updated) 1.1.9
Flare Stack 2.2.10
Flow Control 3.1.3
Automatic Train Fuel Stop 1.1.0
Honk 5.0.0
Nanobots: Early Bots 3.2.16
Recipe Book 3.2.3
Robocharger 1.3.1
Robot Battery Research 0.2.1
✔ Todo List 19.2.0
Calculator UI 1.1.1
Even Distribution 1.0.10
Factory Planner 1.1.31
Factorio Library 0.9.2
Grappling Gun 0.3.2
More Long Inserters 4.1.5
Shield Projector 0.1.3
Factorio Standard Library 1.4.6

**Describe the bug**
When trying to install mod with the factorio server manager I'm getting an error: mod does not exist.
When loading the mod manually on server getting error: `Error in getting mod details from mod portal: {"message":"Mod not found"} `.
The game is still loading correctly with the mod working. It's just a little inconvenient have to remove mod from server to update or install other mods. Mod appears in server mod list as: `Flying car 0.1.0`

**To Reproduce**
Don't know how to help to reproduce... note reproducible in game but in the Factorio Server Manager:

Try to install mod:
1. Go to mods page (link in the menu of the left)
2. Click "Install Mod" tab
3. Login with your factorio credentials
4. In search field search for "AircraftRealism"
5. Install version 1.4.0 by clicking the little dowload button on le right of the version name
6. Getting the error

Load mod manually:
1. Go to mods page (link in the menu of the left)
2. Click "Upload Mod" tab
3. Select Aircraft Realism zip file from system
4. Click upload button
5. Getting the error

**Expected behavior**
I expect having no error on trying to install or load mod on server... 

**Additional context**
Have no more context in head, if you need more information feel free to ask me, thx
![aircraft_realism_server_install_error](https://user-images.githubusercontent.com/77306553/149991161-aa117803-93eb-4d2e-8f52-248e28b4a751.png)
![aircraft_realism_server_install_error2](https://user-images.githubusercontent.com/77306553/149991162-bd70e067-2d7f-4ef6-9221-a68c52c31921.png)

**Comment by jaihysc** [comment]
`Flying car 0.1.0` is the example mod included with AircraftRealism showing how to create your own aircraft. I am assuming it shows up because of how Factorio Server Manager searches for mods.

You are safe to delete it and AircraftRealism will work with no issues. If it still sees `FlyingCar 0.1.0`, delete `Docs/` from AircraftRealism.

**Comment by zallaevan** [comment]
+1
@jaihysc Yes, but if we were to delete the Flying car mod, how can we install AircraftRealism? Even though I have tried with uploading the zip file, it can't be installed.
