### ISSUE TITLE
Biter damage when flying

### ISSUE THREAD

**Issue by OldStarchy** [jaihysc/Factorio-AircraftRealism#19]
**General questions**
* Does the issue persist after updating to the latest version? Yes
* Does the issue persist with all other mods disabled? untested

**General information**
* Factorio version: unknown (latest as of 2022/10/20)
* Mod version: unknown (latest as of 2022/10/20)
* Other installed mods: Aircraft, (and others, ask for details. No other aircraft/helicopter mods)

**Describe the bug**
Aircraft take damage when flying over biters

**To Reproduce**
1. Hop in an aircraft
2. Fly over a group of aliens

**Expected behavior**
Biters cannot damage airborne aircraft

**Additional context**
If this is intentional, please add an option to disable it. It makes the gunship practically useless as it's nearly impossible to see where you're going at full speed (even without afterburners) and flying over a nest or a group of aliens almost always destroys the aircraft.

**Comment by jaihysc** [comment]
I agree with you, from my experience it is very easy to get the aircraft destroyed. However, right now I cannot think of a way to make it immune against biters (not spitters) only. 
- Giving the aircraft physical resistance also prevents it from being shot by bullets
- Removing the flag "player-creation", the biters still attack the plane if you attack them

**Comment by OldStarchy** [comment]
In that case, I'd rather they'd also be immune to spitters. just lost another fully loaded gunship flying over a single biter at full speed. Can this be made configurable?

**Comment by jaihysc** [comment]
Giving acid immunity would make it immune against worms and spitters in vanilla, however if any mods add acid damage type it would also be immune against that.
I might be able make use of the events to give health back to the plane and make it appear the ship is immune, though the bugs would still follow you around.

**Comment by jaihysc** [comment]
Good news, I figured out a method to make the plane immune against attacks by adding health back when the plane is damaged (using `on_entity_damaged`). When I have time, I will implement a system to make it immune against specific enemy attacks only.

**Comment by jaihysc** [comment]
Setting is available in 1.5.1 to make airborne planes immune. I kept it simple and made it so the plane is immune to all damage for now.
