### ISSUE TITLE
Visualize flight altitude via shadows

### ISSUE THREAD

**Issue by ZXQWAS** [jaihysc/Factorio-AircraftRealism#2]
I tried this mod and saw that there is no visual change in altitude when a plane takes off. Just the disappearing of the shadow is indicative, but not enough. Would be pleasing to see this like it's done in Raven.

**Comment by jaihysc** [comment]
I unfortunately am by no means skilled enough to create sprites to visualize the change in altitude.
Hence the reason I made the source code openly available in case someone wishes to improve my work in the future.

For the time being, this is the best I can do

**Comment by jaihysc** [comment]
The shadows are baked onto the main sprites of the planes, there is the shadow-less versions, but they have artifacts from what looks to be a messy erase all

**Comment by jaihysc** [comment]
It has been a while, this issue has recently came back to my head,

It is possible for flight altitude to be visualized by having a separate shadow for each plane and make all the planes shadowless. During flight, the shadow can be rendered to different positions to visualize altitude.

**Comment by Stifling-Bossness** [comment]
There was an old Aircraft [add-on mod](https://forums.factorio.com/viewtopic.php?f=94&t=31563) that had this functionality, unfortunately it wasn't updated to 0.16 so not sure if the relevant code would even work anymore.

**Comment by jaihysc** [comment]
Animated shadows added as of v1.5.0
