### ISSUE TITLE
Feature request: Per vehicle option for water landing

### ISSUE THREAD

**Issue by TurretProblems** [jaihysc/Factorio-AircraftRealism#20]
In line 26 of planeCollisions.lua the mod defines what counts as a water landing and promptly kills the player
I would like to suggest making a tag for aircrafts. (easiest way to me seems to be a setting in the mod settings menu for a specific craft)

While what I am trying to achieve for my friends an I playthrough is possible without aircraft realism, the rest of the features are greatly desired.

For reference I was intending to make a PBY5 Catalina mod to go along with my friends coastal/ archipelago playthrough where we have mods to allow us to traverse shallow water.

**Comment by jaihysc** [comment]
What I could do is allow you to specify whether the plane can land on water when [creating a new plane](https://github.com/jaihysc/Factorio-AircraftRealism/blob/master/Docs/AddingNewPlanes.md). Is that what you are thinking of, or do you want all planes to to be configured to land on water?

Adding a new option for landing on water would require authors of other aircraft mods to add the option as well, which I don't think is a good idea.

**Comment by TurretProblems** [comment]
You make a good point, allowing that option on new planes makes the most sense, didnt realize it would require configuration on the plane-makers part. Also thanks for the quick response!

**Comment by TurretProblems** [comment]
Ive gotten as far as making a complete vehicle, I'm now wondering if a texture change would be possible depending on if its landed, the aii-ironclad always has the lower half partially transparent as its always in water, the only other thing i can think to do for that would be to overlay some other sprite at the waterline to make it look more convincing

Perhaps its not ideal for me to think out-loud here, but i can show you some progress.
![image](https://github.com/jaihysc/Factorio-AircraftRealism/assets/14169244/fb87450b-e45b-4f4b-8c6e-36dfa2c4570f)

**Comment by jaihysc** [comment]
The mod creates a copy of planes for an airborne plane and the landed plane. You could change the texture of the landed plane. However, it will also appear that way on the ground, and it will suddenly change textures when it takes off (becomes airborne version).

The best idea I can think of would be as you said, to overlay another sprite. That is how I achieved the shadow animation for takeoff. Do note it is actually quite tricky to overlay another sprite correctly, when the plane rotates and moves.

I could provide a method for you to specify a sprite to render over the plane, something like the following.

```lua
aircraftMaker.makeAirborne({
    name="cool-plane",
    onRender=function(position, spriteIndex)
        -- Render things
    end
})
```

**Comment by TurretProblems** [comment]
that would be fun, though that would mean rendering certain planes with two layers to fit the waterline sprite inbetween, but that can certainly be done. that would be very cool indeed thank you!

**Comment by jaihysc** [comment]
I tried to implement `onRender` for you and realized it might be difficult to provide a general method. I think it would be better if you implemented it yourself. Here is some example code on how it could be done.

```lua
script.on_event(defines.events.on_tick, function(event)
    for index, player in pairs(game.connected_players) do
        if player and
           player.driving and
           player.vehicle and
           player.surface and
           player.vehicle.name == 'cool-plane' then

            -- [[ Here we calculate where to place the sprite ]]

            -- Since the sprite trails by 1 tick, we account for it by moving the sprite forwards using the plane's velocity
            -- Speed in tiles/tick
            local spriteOffsetX = player.vehicle.speed * math.sin(2*math.pi*player.vehicle.orientation)
            local spriteOffsetY = player.vehicle.speed * -math.cos(2*math.pi*player.vehicle.orientation)

            -- Use the vehicle position, if the player's position is used, the shadow flickers
            -- briefly on takeoff
            local spritePositionX = player.vehicle.position.x + spriteOffsetX
            local spritePositionY = player.vehicle.position.y + spriteOffsetY


            -- [[ Perform orthogonal projection to calculate the orientation ]]
            local totalFrames = 10 -- This is the number of frames for your plane's orientations
            local orientation = player.vehicle.orientation + 0.25
            local x = math.sin(orientation * math.pi * 2)
            local y = -math.cos(orientation * math.pi * 2)
            y = y * math.cos(math.pi / 4)
            local deprojectedOrientation = (math.atan2(x, -y) / (math.pi * 2)) - 0.25
            local spriteIdx = math.floor((deprojectedOrientation * totalFrames) + 0.5) % totalFrames


            -- [[ You need to create a sprite of your overlay to correspond to each frame of the plane's orientations ]]
            -- In this case, it selects cool-plane-overlay-0, cool-plane-overlay-1, ...
            rendering.draw_sprite{
                sprite = "cool-plane-overlay-" .. tostring(spriteIdx),
                target = {spritePositionX, spritePositionY},
                surface = player.surface,
                time_to_live = 2
            }
        end
    end
end
```

**Comment by TurretProblems** [comment]
Didn't realize github was able to visualize that, also thats quite alright about the rendering feature,also like you said since there is one vehicle for on teh ground and one in the air i can just make it a water only vehicle (which was the intention anyways) and fade the lower body, in the meantime ive made a python script to make the tilemap for me meaning my workflow is now almost entirely offline. Aircraft realism will 100% end up being a required mod for this new plane so thats good news for you too! ive also prettied up the graphics quite a bit and am in the midst of "factorioifying" the plane a bit more

**Comment by TurretProblems** [comment]
I have got everything working, mostly the mod is released and im tuning the speeds, otherwise shes done and integrated with your mod, she still explodes on water though which is hilarious

**Comment by jaihysc** [comment]
Here is an updated mod with the option to allow planes to land on water [AircraftRealism_1.5.5.zip](https://github.com/jaihysc/Factorio-AircraftRealism/files/11712375/AircraftRealism_1.5.5.zip), use it like this

```lua
local aircraftMaker = require("__AircraftRealism__.aircraftMaker")
local groundedGunship = data.raw["car"]["gunship"]
aircraftMaker.makeGrounded({
    isSeaplane = true, -- Set this option here
    prototype = groundedGunship
})
```

**Comment by TurretProblems** [comment]
Will do!

**Comment by TurretProblems** [comment]
![image](https://github.com/jaihysc/Factorio-AircraftRealism/assets/14169244/d1d3e0de-85d5-46cc-a17b-f95f4699774d)

It works! excellent!
As soon as you push the update I will update mine as well, everything seems to work as expected, thank you very much!

**Comment by TurretProblems** [comment]
So i use 8 stripes of 2x8 for my sprite sheet, if i wanted to change the texture of the airborne plane, would i just use the same exact syntax in the makeAirborne, with a different set of sheets?
Also ive noticed it does not remove the shadow of the airborne vehicle

(this is where im asking if i just define a different spritesheet for the airborne one)
`local flying = aircraftMaker.makeAirborne({
    name="PBY5",
    shadow={
        filename="__AC-Aircraft__/graphics/PBY5-shadow.png",
        width = 512,
        height = 512,
        shift = util.by_pixel(0, -60),

        hrFilename="__AC-Aircraft__/graphics/PBY5-shadow.png",
        hrWidth = 512,
        hrHeight = 512,
        hrShift = util.by_pixel(0, -60),
        hrScale = 1.25,

        lineLength = 8,
        directionCount = 64,
        endSpeed = 55.9 / 240,
    }
})`

**Comment by TurretProblems** [comment]
So i use 8 stripes of 2x8 for my sprite sheet, if i wanted to change the texture of the airborne plane, would i just use the same exact syntax in the makeAirborne, with a different set of sheets?
Also ive noticed it does not remove the shadow of the airborne vehicle

(this is where im asking if i just define a different spritesheet for the airborne one)

`
local flying = aircraftMaker.makeAirborne({
    name="PBY5",
    shadow={
        filename="__AC-Aircraft__/graphics/PBY5-shadow.png",
        width = 512,
        height = 512,
        shift = util.by_pixel(0, -60),

        hrFilename="__AC-Aircraft__/graphics/PBY5-shadow.png",
        hrWidth = 512,
        hrHeight = 512,
        hrShift = util.by_pixel(0, -60),
        hrScale = 1.25,

        lineLength = 8,
        directionCount = 64,
        endSpeed = 55.9 / 240,
    }
})
`

**Comment by TurretProblems** [comment]
so heres a problem, i need to swap which texture im using based on whether the vehicle is landed or not, ive just tried making another entity with the other texture and is otherwise identical save for adding a bit onto the entity name, and i figured makeAirborne would be okay with this, but i realize now it specifically wants the one that was used in makeGrounded.
Im not sure what the best way to go about this is.

otherwise everything is done as far as gameplay is concerned.

Also the airborne version of the vehicle does not have its shadow removed.

**Comment by jaihysc** [comment]
You can change the texture of the landed and airborne plane as they are separate. You have to manually remove the shadows from the airborne version, like this

```lua
local groundedPlane = data.raw["car"]["myplane"]
-- Change textures of grounded plane here
aircraftMaker.makeGrounded({prototype=groundedPlane})

local airbornePlane = aircraftMaker.makeAirborne({name="myplane"})
-- Change textures of airborne plane here
```

**Comment by TurretProblems** [comment]
Thank you very much!
