### ISSUE TITLE
Build Events when switching landing and takeoff planes

### ISSUE THREAD

**Issue by OnigiriOni** [jaihysc/Factorio-AircraftRealism#22]
I am writing a mod that tracks entities on creation (build events) and I am unable to keep track of aircrafts that transition between takeoff and landing. When they are deleted and a new entity is created it does not raise a build event. That means I am left with an invalid entity and the new entity goes to the nether.

Could you include the necessary changes to raise the events?:
```
LuaEntity::destroy{raise_destroy=true}
LuaSurface::create_entity{raise_built=true}

```

**Comment by OnigiriOni** [comment]
I took the freedom to make a PR for my desired changes. Its very minor and should not interfere with anything. Please take a look at it and let me know if it's ok. Meanwhile I am settled with a copy of the PR if the changes are undesired.
Thanks for the great mod.

PS: I haven't looked at it but would the big data string mod help with the need to store the aircraft data over multiple prototype instances?

**Comment by jaihysc** [comment]
PR #23.

Never heard of the big data string mod before, I will check it out, thanks.
