### ISSUE TITLE
Aircraft-space-age: Preliminary support causes crash when entering plane

### ISSUE THREAD

**Issue by nicholasgower** [jaihysc/Factorio-AircraftRealism#27]
**General questions**
* Does the issue persist after updating to the latest version?
* Does the issue persist with all other mods disabled?

**General information**
* Game version: 2.0.21
* Mod version: 2.0.0
* Other mods: Aircraft-space-age (dev version: https://github.com/nicholasgower/Aircraft-Space-Age/tree/dev-AircraftRealism)

**Describe the bug**
After placing any aircraft with support for AircraftRealism(Gunship, Cargo Ship, Jet, Flying Fortress), and attempting to drive the plane, either in person or remotely, will crash the game with the following error:

```Error while running event AircraftRealism::on_tick (ID 0)
__AircraftRealism__/logic/utility.lua:248: attempt to index field '?' (a nil value)
stack traceback:
	__AircraftRealism__/logic/utility.lua:248: in function 'getTransitionSpeed'
	__AircraftRealism__/logic/gaugeController.lua:161: in function 'updateGaugeArrows'
	__AircraftRealism__/logic/gaugeController.lua:204: in function 'handler'
	__AircraftRealism__/control.lua:48: in function <__AircraftRealism__/control.lua:40>```

**To Reproduce**
Steps to reproduce the behavior:
1. Place any aircraft with support for AircraftRealism(Gunship, Cargo Ship, Jet, Flying Fortress) on the ground.
2. Enter the plane.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Additional context**
It's possible that my support for AircraftRealism was written incorrectly. I'd appreciate assistance if that is the case.

**Comment by jaihysc** [comment]
The setting needs to be type `runtime-global`, not startup
You have that error because it cannot find the setting at runtime

https://github.com/nicholasgower/Aircraft-Space-Age/blob/b53528d4f6a512bea59e8ace4b4103e6b9cc2d0d/settings.lua#L111
