### ISSUE TITLE
[Aircraft-space-age dev branch] Planes that take off and land are unminable

### ISSUE THREAD

**Issue by nicholasgower** [jaihysc/Factorio-AircraftRealism#28]
**General information**
* Factorio 2.0.23

* Mod version: 2.0.1
**Other installed mods:**
* Aircraft-space-age (dev branch as of bug report: https://github.com/nicholasgower/Aircraft-Space-Age/tree/e93b91532ff372f6803a6f0315dc035853bae378)
* Space Age DLC

**Describe the bug**
When aircraft-space-age (dev branch) and Aircraft Realism are installed, when an aircraft takes off and lands, the aircraft goes from being minable to being unminable.

**To Reproduce**
1. Download this test scenario. [aircraft test.zip](https://github.com/user-attachments/files/17983485/aircraft.test.zip)
2. Install the dev branch of aircraft-space-age as of this bug report. 
3. Load the scenario. Aircraft-space-age, aircraft-realism, and Space Age should all load.
4. To the player's right are the eight aircraft in Aircraft-space-age. Confirm that they are all minable.
![image](https://github.com/user-attachments/assets/5758728c-d5fc-4db8-9675-e120228cddb3)
6. Attempt to fly any one of the aircraft. They will takeoff and land as expected.
7. After landing the aircraft, attempt to mine the aircraft.

**Expected behavior**
All aircraft should be minable by default. Aircraft realism should not meddle in whether aircraft are minable.

**Comment by jaihysc** [comment]
I think this is a bug with Factorio (!?)

Try this, put this in `control.lua`. Place a car, check that you can mine the car. Now enter the car, the assert should not fail

```lua
script.on_event(defines.events.on_tick, function(e)
    for index, player in pairs(game.connected_players) do
        if player and player.driving and player.vehicle then
            player.vehicle.minable = true
            assert(player.vehicle.minable)
        end
    end
end)
```

**Comment by nicholasgower** [comment]
It looks like all vehicles become unminable once a player enters the vehicle. The assertion fails upon entering any vehicle, including all aircraft and both the vanilla car and tank. I wonder if the transition from grounded to airborne aircraft causes Factorio to forget it needs to make planes minable again once after players leave the vehicle.
![image](https://github.com/user-attachments/assets/2aebb4c6-5600-4371-baa0-8306dae5bafb)

**Comment by nicholasgower** [comment]
It might be necessary to add a script to AircraftRealism that makes sure that vehicles are minable after the player dismounts the vehicle.

**Comment by nicholasgower** [comment]
By the way, I'm putting together a Discord server centered around the Aircraft mod and my other mods. If you are interested in joining to make collaboration easier, here's the link. https://discord.gg/zeuMnRef
