### ISSUE TITLE
Grounded Planes don't collide with water [Hovercraft mod Incompatibility]

### ISSUE THREAD

**Issue by grundyboy34** [jaihysc/Factorio-AircraftRealism#5]
As stated, grounded planes can travel on water as if it were land.
If their speed reaches 0 however, they blow up.

Adding the water-tile collision mask fixes this but also causes them to not be able to cross gates or railroads, so I don't think this is the method that other vehicles such as vanilla cars use.

**Comment by jaihysc** [comment]
From my testing, planes on land are unable to travel into the water.

**Comment by grundyboy34** [comment]
Hmm you're right, it seems to be one of the other mods I have causing the issue.
I'll post here when I figure out which one it is, so other people can know, and possibly find a fix.

**Comment by grundyboy34** [comment]
It's the [Hovercraft](https://mods.factorio.com/mod/Hovercraft) mod.
From what I can tell, it's completely the Hovercraft mod author's fault as they for some reason modify the collision masks of all car type entities.

**Comment by jaihysc** [comment]
I would suggest you report this to the Hovercraft mod author.

They do not seem to have a github repo, so it appears the Factorio mod portal is the only way
