### ISSUE TITLE
Bug in compatibility with Better Cargo Planes

### ISSUE THREAD

**Issue by robot256** [jaihysc/Factorio-AircraftRealism#6]
better-cargo-plane max_health is originally 1000, and even-better-cargo-plane max_health is originally 2000.  This is set correctly in airbornePlanes.lua.  In data-final-fixes.lua, grounded plane health should be 0.5 times the airborne health.  But for better-cargo-plane and even-better-cargo-plane, grounded plane max_health is set to 200 and 400 instead of 500 and 1000.

The result is that when you place those planes, they start with 200 and 400 health respectively.  Then when they take off, they show as having 400/1000 health, and 800/2000 health.

**Comment by jaihysc** [comment]
https://github.com/jaihysc/Factorio-AircraftRealism/blob/e1aacc52664c3636e03d85c32bcebdd7442af291/data-final-fixes.lua#L74

Yeah I see the problem, they have been adjusted accordingly up to 500 and 1000.

Thank you for the report.

**Comment by jaihysc** [comment]
Fixed as of [0.3.5](https://github.com/jaihysc/Factorio-AircraftRealism/tree/8bfc999ece3d286b029dc41bd3ba5fb3388fb1af).
